name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build k3s
      run: |
        docker build . --file Dockerfile --tag k3.5s:${GITHUB_SHA} &&
        id=$(docker create k3.5s:${GITHUB_SHA}) && docker cp ${id}:/usr/local/bin/k3s ${GITHUB_WORKSPACE}/k3s && docker rm -v ${id} && chmod a+x ${GITHUB_WORKSPACE}/k3s
    - uses: actions/upload-artifact@v2
      with:
        name: k3s
        path: k3s
